[package]
name = "ranni"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.6"
ffmpeg-next = "7.1.0"
anyhow = "1.0.98"
clap = { version = "4.5.43", features = ["derive"] }
walkdir = "2.5.0"
